load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "log",
    hdrs = ["log.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//emb/project/base:base_bh_cc",
    ],
)
