services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    container_name: chibisafe
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    container_name: chibisafe-server
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: chibisafe-caddy
    network_mode: service:tailscale
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./uploads:/app/uploads:ro
    environment:
      - BASE_URL=":80"
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    container_name: chibisafe-tailscale
    hostname: files
    secrets:
      - tailnet_oauth
    environment:
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-serve.json
    volumes:
      - chibisafe-ts-authkey:/var/lib/tailscale
      # Use a directory so `fsnotify` can watch the config file for changes
      - ${PWD}/ts-serve:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    command: >
      /bin/sh -c "export TS_AUTHKEY=$$(cat /run/secrets/tailnet_oauth)?ephemeral=false && /usr/local/bin/containerboot"

volumes:
  chibisafe-ts-authkey:
  chibisafe-uploads:
  chibisafe-logs:
  chibisafe-database:


secrets:
  tailnet_oauth:
    file: ${PWD}/../secrets/tailnet_oauth.secret
