load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "setec",
    srcs = ["setec.go"],
    importpath = "nlb/nlb/tailscale/setec",
    visibility = ["//visibility:public"],
    deps = ["@com_github_tailscale_setec//client/setec"],
)
