services:
  redis:
    image: redis:latest
    expose:
      - "6379:6379"
    command: >
      redis-server
      --save 900 1
      --appendonly yes
      --appendfilename "appendonly.aof"
      --dir "/data"
      --requirepass ${DATABASE_PASSWORD}
    volumes:
      - redis:/data
    restart: always
  mariadb:
    image: mariadb:latest
    expose:
      - "3306:3306"
    environment:
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MARIADB_ROOT_HOST=localhost"
      - "MARIADB_DATABASE=scholarsome"
      - "MARIADB_USER=scholarsome"
      - "MARIADB_PASSWORD=${DATABASE_PASSWORD}"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  scholarsome:
    image: hwgilbert16/scholarsome:latest
    platform: "linux/amd64"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
#      - "(your ssl port):8443"
    environment:
      - "NODE_ENV=${NODE_ENV}"
      - "DATABASE_URL=mysql://scholarsome:${DATABASE_PASSWORD}@mariadb:3306/scholarsome"
      - "JWT_SECRET=${JWT_SECRET}"
      - "HTTP_PORT=${HTTP_PORT}"
      - "STORAGE_TYPE=${STORAGE_TYPE}"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_USERNAME="
      - "REDIS_PASSWORD=${DATABASE_PASSWORD}"
      - "STORAGE_LOCAL_DIR=/data"
      - "S3_STORAGE_ENDPOINT=${S3_STORAGE_ENDPOINT}"
      - "S3_STORAGE_ACCESS_KEY=${S3_STORAGE_ACCESS_KEY}"
      - "S3_STORAGE_SECRET_KEY=${S3_STORAGE_SECRET_KEY}"
      - "S3_STORAGE_REGION=${S3_STORAGE_REGION}"
      - "S3_STORAGE_BUCKET=${S3_STORAGE_BUCKET}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "HOST=${HOST}"
      - "SSL_KEY_BASE64=${SSL_KEY_BASE64}"
      - "SSL_CERT_BASE64=${SSL_CERT_BASE64}"
      - "SCHOLARSOME_RECAPTCHA_SITE=${RECAPTCHA_SITE}"
      - "SCHOLARSOME_RECAPTCHA_SECRET=${RECAPTCHA_SECRET}"
    volumes:
      - scholarsome:/data
    depends_on:
      - mariadb
      - redis
    restart: always
volumes:
  redis:
  mariadb:
  scholarsome:
