name: services

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-config:/etc/nginx
      - nginx-html:/usr/share/nginx/html
      - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/secrets/pine.barn-arcturus.ts.net.crt:/etc/nginx/cert.crt:ro
      - ${PWD}/secrets/pine.barn-arcturus.ts.net.key:/etc/nginx/cert.key:ro
    deploy:
      restart_policy:
        condition: always
    command: >
      /bin/sh -c "nginx -g 'daemon off;'"

  lobe-chat:
    image: ghcr.io/ryandraves/lobe-chat:81-setup-pine
    ports:
      - "3210:3210"
    secrets:
      - lobe_chat_password
      - openai_key
    deploy:
      restart_policy:
        condition: on-failure
    user: root
    entrypoint: [ "/bin/sh", "-c", "export ACCESS_CODE=$(cat /run/secrets/lobe_chat_password) && export OPENAI_API_KEY=$(cat /run/secrets/openai_key) && su nextjs -c '/bin/node /app/startServer.js'" ]

  homer:
    image: b4bz/homer:latest
    ports:
      - "1337:8080"
    volumes:
      - ${PWD}/homer:/home/lighttpd
    secrets:
      - portainer_token
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint: '/home/lighttpd/entrypoint.sh'

volumes:
  nginx-config:
  nginx-html:


secrets:
  lobe_chat_password:
    file: ${PWD}/secrets/lobe_chat.password
  openai_key:
    file: ${PWD}/secrets/openai.key
  portainer_token:
    file: ${PWD}/secrets/portainer.token
