version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    network_mode: service:tailscale
    devices:
      # use `python -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - octoprint:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=

  tailscale:
    image: tailscale/tailscale
    container_name: octoprint-tailscale
    hostname: print
    secrets:
      - tailnet_oauth
    environment:
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-serve.json
    volumes:
      - octoprint-ts-authkey:/var/lib/tailscale
      # Use a directory so `fsnotify` can watch the config file for changes
      - ${PWD}/octoprint/ts-serve:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    command: >
      /bin/sh -c "export TS_AUTHKEY=$$(cat /run/secrets/tailnet_oauth)?ephemeral=false && /usr/local/bin/containerboot"

volumes:
  octoprint:
  octoprint-ts-authkey:


secrets:
  tailnet_oauth:
    file: ${PWD}/secrets/tailnet_oauth.secret
