load("@aspect_rules_js//js:defs.bzl", "js_library")

js_library(
    name = "styles",
    srcs = [
        "globals.css",
        "markdown-styles.module.css",
        "switch.module.css",
    ],
    visibility = ["//blog:__subpackages__"],
)
