# @generated by Buffham
import dataclasses
from typing import Self

@dataclasses.dataclass
class SystemFlashPage:
    # Side the microcontroller has booted from;
    # 0 for side A, 1 for side B
    boot_side: int
    # Number of times the microcontroller had booted
    boot_count: int

    def serialize(self) -> bytes: ...

    @classmethod
    def deserialize(cls, buffer: bytes) -> tuple[Self, int]: ...

