# @generated by Buffham
import dataclasses
import enum
from typing import Self, Type

from emb.network.serialize import bh_cobs
from emb.network.transport import transporter
from nlb.buffham import bh

OTHER_CONSTANT = 2

class MyEnum(enum.Enum):
    A = 0
    B = 1


@dataclasses.dataclass
class Pong:
    pong: int

    def serialize(self) -> bytes: ...
    @classmethod
    def deserialize(cls, buffer: bytes) -> tuple[Self, int]: ...

REGISTRY: dict[int, Type[bh.BuffhamLike]] = ...

class OtherSerializer(bh_cobs.BhCobs):
    def __init__(self, registry: bh_cobs.Registry | None = None): ...

class OtherNode[
    CommsTransporter: transporter.TransporterLike,
    LogTransporter: transporter.TransporterLike,
](bh.BhNode[OtherSerializer, CommsTransporter, LogTransporter]):
    def __init__(
        self,
        serializer: OtherSerializer | None = None,
        comms_transporter: CommsTransporter | None = None,
        log_transporter: LogTransporter | None = None,
    ): ...

PONG: bh.Transaction[Pong, Pong] = ...
