filegroup(
    name = "assets",
    srcs = [
        "icon-180.png",
        "icon-192.png",
        "icon-512.png",
        "index.html",
        "login.html",
        "manifest.webmanifest",
        "style.css",
    ],
    visibility = ["//apps/euc:__pkg__"],
)
