"""Convert a WAV file into a C++ `emb::yaal::AudioClip` source pair.

The generated `.cc` embeds the clip as interleaved 16-bit stereo PCM, suitable
for direct DMA to an I2S PIO program on the Pico.
"""

import pathlib

import numpy as np
import rich_click as click
from scipy import signal
from scipy.io import wavfile

SAMPLES_PER_LINE = 12

HPP_TEMPLATE = """\
// Generated by //nlb/wav:wav2cc from {source}. Do not edit.
#pragma once

#include "emb/yaal/audio_clip.hpp"

namespace {namespace} {{

extern const emb::yaal::AudioClip {symbol};

}}  // namespace {namespace}
"""

CC_TEMPLATE = """\
// Generated by //nlb/wav:wav2cc from {source}. Do not edit.
#include "{header_include}"

namespace {namespace} {{
namespace {{

alignas(4) const int16_t {symbol}_samples[{num_samples}] = {{
{sample_rows}
}};

}}  // namespace

const emb::yaal::AudioClip {symbol} = {{
    .sample_rate = {sample_rate},
    .num_frames = {num_frames},
    .samples = {symbol}_samples,
}};

}}  // namespace {namespace}
"""


def convert_samples(
    data: np.ndarray,
    input_rate: int,
    sample_rate: int,
    gain_db: float,
    pad_ms: int,
) -> np.ndarray:
    """Convert WAV samples to interleaved 16-bit stereo PCM.

    Args:
        data: Samples as loaded by `scipy.io.wavfile.read`, shape (n,) for
            mono or (n, channels) for multi-channel.
        input_rate: Sample rate of `data`, in Hz.
        sample_rate: Target sample rate, in Hz.
        gain_db: Gain to apply, in dB.
        pad_ms: Zero-padding to append, in milliseconds.

    Returns:
        Array of int16 samples, shape (frames, 2).
    """
    # Normalize to float32 in [-1, 1)
    if data.dtype == np.uint8:
        samples = (data.astype(np.float32) - 128.0) / 128.0
    elif data.dtype in (np.int16, np.int32):
        samples = data.astype(np.float32) / -np.iinfo(data.dtype).min
    elif data.dtype in (np.float32, np.float64):
        samples = data.astype(np.float32)
    else:
        raise ValueError(f'Unsupported WAV sample format: {data.dtype}')

    # Normalize shape to (frames, 2)
    if samples.ndim == 1:
        samples = np.stack([samples, samples], axis=-1)
    elif samples.shape[1] == 1:
        samples = np.repeat(samples, 2, axis=1)
    elif samples.shape[1] == 2:
        pass
    else:
        raise ValueError(f'Unsupported channel count: {samples.shape[1]}')

    if input_rate != sample_rate:
        gcd = np.gcd(input_rate, sample_rate)
        samples = signal.resample_poly(
            samples, sample_rate // gcd, input_rate // gcd, axis=0
        )

    samples *= 10.0 ** (gain_db / 20.0)

    pad_frames = (sample_rate * pad_ms) // 1000
    samples = np.concatenate([samples, np.zeros((pad_frames, 2), dtype=np.float32)])

    return np.clip(np.round(samples * 32768.0), -32768, 32767).astype(np.int16)


def generate_hpp(source: str, namespace: str, symbol: str) -> str:
    return HPP_TEMPLATE.format(source=source, namespace=namespace, symbol=symbol)


def generate_cc(
    source: str,
    header_include: str,
    namespace: str,
    symbol: str,
    sample_rate: int,
    samples: np.ndarray,
) -> str:
    flat = samples.flatten()
    rows = []
    for offset in range(0, flat.size, SAMPLES_PER_LINE):
        row = ', '.join(
            str(sample) for sample in flat[offset : offset + SAMPLES_PER_LINE]
        )
        rows.append(f'    {row},')

    return CC_TEMPLATE.format(
        source=source,
        header_include=header_include,
        namespace=namespace,
        symbol=symbol,
        num_samples=flat.size,
        sample_rows='\n'.join(rows),
        sample_rate=sample_rate,
        num_frames=samples.shape[0],
    )


@click.command()
@click.option(
    '--input',
    '-i',
    type=click.Path(exists=True, dir_okay=False, path_type=pathlib.Path),
    required=True,
    help='Input WAV file',
)
@click.option(
    '--output-hpp',
    type=click.Path(dir_okay=False, path_type=pathlib.Path),
    required=True,
    help='Output C++ header file',
)
@click.option(
    '--output-cc',
    type=click.Path(dir_okay=False, path_type=pathlib.Path),
    required=True,
    help='Output C++ source file',
)
@click.option(
    '--header-include',
    required=True,
    help='Include path of the generated header, e.g. `emb/project/punbox/rimshot.hpp`',
)
@click.option(
    '--symbol',
    required=True,
    help='Name of the generated `AudioClip` symbol',
)
@click.option(
    '--namespace',
    default='emb::yaal::clips',
    show_default=True,
    help='C++ namespace for the generated symbol',
)
@click.option(
    '--sample-rate',
    type=int,
    default=22050,
    show_default=True,
    help='Target sample rate, in Hz',
)
@click.option(
    '--gain-db',
    type=float,
    default=0.0,
    show_default=True,
    help='Gain to apply, in dB',
)
@click.option(
    '--pad-ms',
    type=int,
    default=50,
    show_default=True,
    help='Zero-padding to append, in milliseconds',
)
def main(
    input: pathlib.Path,
    output_hpp: pathlib.Path,
    output_cc: pathlib.Path,
    header_include: str,
    symbol: str,
    namespace: str,
    sample_rate: int,
    gain_db: float,
    pad_ms: int,
):
    input_rate, data = wavfile.read(input)
    samples = convert_samples(data, input_rate, sample_rate, gain_db, pad_ms)

    output_hpp.write_text(generate_hpp(input.name, namespace, symbol))
    output_cc.write_text(
        generate_cc(input.name, header_include, namespace, symbol, sample_rate, samples)
    )

    print(f'Generated {output_hpp}')
    print(f'Generated {output_cc}')


if __name__ == '__main__':
    main(prog_name='wav2cc')
