#pragma once

#include <cinttypes>

namespace emb {
namespace yaal {

// A Pulse Code Modulation (PCM) audio clip, typically generated by
// `//nlb/wav:wav2cc` and stored in flash.
struct AudioClip {
    // Sample rate, in Hz
    uint32_t sample_rate;
    // Number of stereo frames; each frame is two int16_t samples (L then R)
    uint32_t num_frames;
    // Interleaved L/R samples, `2 * num_frames` in length
    const int16_t *samples;
};

}  // namespace yaal
}  // namespace emb
