# @generated by Buffham
import dataclasses
from typing import Self, Type

from emb.network.serialize import bh_cobs
from emb.network.transport import transporter
from nlb.buffham import bh

from emb.project.base import base_bh

@dataclasses.dataclass
class PunboxState:
    # Number of debounced button presses (and remote triggers) since boot
    press_count: int
    # 1 if the clip is currently playing
    playing: int

    def serialize(self) -> bytes: ...
    @classmethod
    def deserialize(cls, buffer: bytes) -> tuple[Self, int]: ...

REGISTRY: dict[int, Type[bh.BuffhamLike]] = ...

class PunboxSerializer(bh_cobs.BhCobs):
    def __init__(self, registry: bh_cobs.Registry | None = None): ...

class PunboxNode[
    CommsTransporter: transporter.TransporterLike,
    LogTransporter: transporter.TransporterLike,
](bh.BhNode[PunboxSerializer, CommsTransporter, LogTransporter]):
    def __init__(
        self,
        serializer: PunboxSerializer | None = None,
        comms_transporter: CommsTransporter | None = None,
        log_transporter: LogTransporter | None = None,
    ): ...

# Trigger clip playback, as if the button were pressed
PLAY_SOUND: bh.Transaction[base_bh.Ping, PunboxState] = ...
# Read the current state without triggering playback
GET_STATE: bh.Transaction[base_bh.Ping, PunboxState] = ...
