# @generated by Buffham
import dataclasses
from typing import Self, Type

from emb.network.serialize import bh_cobs
from emb.network.transport import transporter
from nlb.buffham import bh

from emb.project.base import base_bh

@dataclasses.dataclass
class DistanceMeasurement:
    # Timestamp relative to device boot, in milliseconds.
    # The timestamp is collected immediately following the measurement
    timestamp_ms: int
    # Measured distance, in millimeters
    distance_mm: int

    def serialize(self) -> bytes: ...
    @classmethod
    def deserialize(cls, buffer: bytes) -> tuple[Self, int]: ...

REGISTRY: dict[int, Type[bh.BuffhamLike]] = ...

class Robo24Serializer(bh_cobs.BhCobs):
    def __init__(self, registry: bh_cobs.Registry | None = None): ...

class Robo24Node[
    CommsTransporter: transporter.TransporterLike,
    LogTransporter: transporter.TransporterLike,
](bh.BhNode[Robo24Serializer, CommsTransporter, LogTransporter]):
    def __init__(
        self,
        serializer: Robo24Serializer | None = None,
        comms_transporter: CommsTransporter | None = None,
        log_transporter: LogTransporter | None = None,
    ): ...

GET_MEASUREMENT: bh.Transaction[base_bh.Ping, DistanceMeasurement] = ...
