load(":workspace_tool.bzl", "workspace_tool")

workspace_tool(
    name = "buildifier",
    tool = "@buildifier_prebuilt//:buildifier",
)

workspace_tool(
    name = "picotool",
    tool = "//tools/rpi_picotool:picotool_bin",
)
