#!/bin/bash
#
# Generate a Python file with global variables matching the build stamp

stable_status_file="$1"
output_file="$2"

if [ -z "$stable_status_file" ] || [ -z "$output_file" ]; then
  echo "Usage: $0 <stable_status_file> <output_file>"
  exit 1
fi

# Read the stable status file to get the commit and label
# the file is arranged as `KEY VALUE` lines and may not exist
commit=$(grep -s -E '^STABLE_GIT_COMMIT ' "$stable_status_file" | cut -d ' ' -f 2 | tr -d "'")
label=$(grep -s -E '^BUILD_EMBED_LABEL ' "$stable_status_file" | cut -d ' ' -f 2 | tr -d "'")

# If the variables are not found, set them to empty strings
if [ -z "$commit" ]; then
  commit=""
fi
if [ -z "$label" ]; then
  label=""
fi

# Write the variables to the output file
cat <<EOF > "$output_file"
# Generated by version.sh
# This file is automatically generated and should not be edited manually.
GIT_COMMIT = '$commit'
VERSION = '$label'
EOF
