# https://lobehub.com/docs/self-hosting/environment-variables
# Needed to override the default base path for the Lobe Chat app
# Sigh...
name: Build Custom LobeHub Image

on:
  workflow_dispatch:
    inputs:
      arm:
        description: 'Build for ARM architecture'
        required: false
        default: true
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/lobe-chat

jobs:
  build-and-push:
    # Only MacOS runners are available for ARM builds
    runs-on: ${{ inputs.arm == 'true' && 'macos-latest' || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: lobehub/lobe-chat

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_BASE_PATH=/chat
