# Workflow for building and deploying a site to GitHub Pages
name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to GitHub Pages"
        default: true
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Bazel Cache
        uses: actions/cache@v4
        with:
          # Path must match `build --disk_cache=` in the .bazelrc
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-${{ github.workflow }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build Site
        id: build_site
        run: |
          bazel build //blog:next
          # Set the output path as an output variable
          echo "out_path=bazel-bin/blog/out" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.build_site.outputs.out_path }}

  deploy:
    if: github.event_name == 'push' || github.event.inputs.deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
