name: Python Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common Setup
        run: |
          sudo apt-get install -y portaudio19-dev
          echo "build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}" > .user.bazelrc

      - name: Prepare Python release
        run: |
          ./tools/release/python/update_build.sh --bump-${{ github.event.inputs.bump_type }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'Prepare Python release (${{ github.event.inputs.bump_type }} bump)'
          branch: 'release/python-bump-${{ github.event.inputs.bump_type }}'
          title: 'Python Release: ${{ github.event.inputs.bump_type }} bump'
          sign-commits: true
          draft: true
          body: |
            Automated PR for a ${{ github.event.inputs.bump_type }} bump to the Python package version.

            The package will be published to PyPI after this PR is merged.
