# Do the Bazel thing
name: Test All

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up apt
        run: |
          sudo apt-get install -y zlib1g-dev libtinfo-dev
          strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
          # portaudio19-dev libc6 libstdc++6 libglib2.0-dev
      - name: Configure Bazel
        run: |
          echo "build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}" > .user.bazelrc
      - name: Build
        run: |
          bazel build //...
      - name: Test
        run: |
          bazel test //...
