# Do the Bazel thing
name: Test All

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Common Setup
        run: |
          sudo apt-get install -y portaudio19-dev
          echo "build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}" > .user.bazelrc
      - name: Build
        run: |
          bazel build //... --deleted_packages=apps
      - name: Test
        run: |
          bazel test //... --deleted_packages=apps
