# Do the Bazel thing
name: Test All

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          bazel build //...
      - name: Test
        run: |
          bazel test //...
