# Do the Bazel thing
name: Test All

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up apt
        run: |
          sudo apt-get install -y portaudio19-dev
      # TODO: Not enough disk space for Bazel
      - name: Build
        run: |
          bazel build //nlb/... //emb/...
      - name: Test
        run: |
          bazel test //nlb/... //emb/...
