# Do the Bazel thing
name: Test All

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show disk usage
        run: df -h

      - name: Top-level directories
        run: du -h -d1 / | sort -hr | head -n 20

      - name: Detailed file sizes
        run: find / -type f -exec du -h {} + 2>/dev/null | sort -hr | head -n 100

      - name: Common Setup
        run: |
          sudo apt-get install -y portaudio19-dev
          echo "build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}" > .user.bazelrc
      - name: Build
        run: |
          bazel build //... --deleted_packages=apps
      - name: Test
        run: |
          bazel test //... --deleted_packages=apps
