filegroup(
    name = "openai_key",
    srcs = ["openai.key"],
)

filegroup(
    name = "certs",
    srcs = glob([
        "certs/*.barn-arcturus.ts.net.crt",
        "certs/*.barn-arcturus.ts.net.key",
    ]),
)
